# CONFIG_STM32_BOARD=y
# CONFIG_STM32_PICSIMLAB=n

CONFIG_GPIO=y
CONFIG_DMA=y

# Debug Configuration
CONFIG_DEBUG=y
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_SYMTAB=n

# Console for debug output
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_PRINTK=y
CONFIG_UART_ASYNC_API=y

# Optional: Enable debug thread info
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_THREAD_MONITOR=y
CONFIG_THREAD_NAME=y

# Enable time slicing for threads
CONFIG_TIMESLICING=y

# Set the time slice duration (in milliseconds)
CONFIG_TIMESLICE_SIZE=10

# Time slice priority threshold
CONFIG_TIMESLICE_PRIORITY=1

# Set maximum number of preempt priorities
CONFIG_NUM_PREEMPT_PRIORITIES=127

# Set cooperative thread priorities
CONFIG_NUM_COOP_PRIORITIES=128