/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "common.h"
#include "bsp.h"

int main(void)
{
    /* Loop forever */
	uart_init();
	uart_string_print(BOARD_NAME);
	uart_string_print("\nApplication running\n");
	led_init();
	led_on(LD3);
//	for(;;);
}

void HardFault_Handler(void)
{
	uart_string_print("Application HardFault handler\n");
	led_on(LD4);
}
