/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "common.h"
#include "bsp.h"

#define APPLICATION_STACK_ADDRESS		(0x8010000) // Address of the application in flash memory

typedef void (*jump_to_app)(void);
jump_to_app jump_to_application = *(jump_to_app)0x8010004; // Address of the application in flash memory

int main(void)
{
    /* Loop forever */
	uart_init();
	uart_string_print(BOARD_NAME);
	uart_string_print("\nBootloader entered\n");
	led_init();
	led_on(LD6);
	uint32_t app_stack_pointer = *(uint32_t *)APPLICATION_STACK_ADDRESS; // Read the stack pointer from the application vector table
	uint32_t app_reset_handler_address = *(uint32_t *)(APPLICATION_STACK_ADDRESS + 0x04); // Read the reset handler address from the application vector table
		if (app_reset_handler_address == 0xFFFFFFFF) {
			jump_to_application = NULL; // No application present, stay in bootloader
		}
		else {
			jump_to_application = (jump_to_app)app_reset_handler_address; // Set the jump address to the application reset handler
			if (app_stack_pointer == 0xFFFFFFFF) {
				jump_to_application = NULL; // No application present, stay in bootloader
			}
			else {
				__disable_irq();
				__disable_fault_irq();
				__set_MSP(app_stack_pointer); // Set the main stack pointer to the application's stack pointer
				uart_string_print("Jumping to application\n");
				while(!(UART_PERIPH->SR & USART_SR_TC));
//				uart_deinit();
//				__DSB();
//				__ISB();
				jump_to_application();
		}
	}
	uart_string_print("Re-entered Bootloader\n");
	led_off(LD6);
	for(;;);
}

void HardFault_Handler(void)
{
	if(UART_PERIPH->CR1 & USART_CR1_UE)
	{
		uart_string_print("Bootloader HardFault Handler\n");
	}
	led_on(LD5);
	while(1);
}
