/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "common.h"
#include "bsp.h"
#include "main.h"

queue_t TxQueue = {0};
queue_t RxQueue = {0};

void PrintReceived(void)
{
	if(RxQueue.number_of_elements_inserted > 0U)
	{
		uint16_t number_of_elements_to_display = RxQueue.number_of_elements_inserted;
		queue_pop((void *)&RxQueue, (void *)&TxQueue.storage, RxQueue.number_of_elements_inserted);
		TxQueue.number_of_elements_inserted = number_of_elements_to_display;
		TxQueue.push_index = (TxQueue.push_index + number_of_elements_to_display) % sizeof(TxQueue.storage);
		uart_send((void *)TxQueue.storage, TxQueue.number_of_elements_inserted);
	}
}

void HardFault_Handler(void)
{
	uart_string_print("Application HardFault handler\n");
	led_on(LD4);
}

void compare_strings(const char * str1, const char * str2, ...)
{
	va_list args;
	va_start(args, str2);
	uint32_t number_of_characters_to_compare = va_arg(args, uint32_t);
	if(number_of_characters_to_compare != NULL)
	{
		while(true)
		{

		}
	}
}

void display_menu(const display_menu_states new_state)
{
	static display_menu_states current_state = DISPLAY_INIT;
	if(new_state != current_state)
	{
		current_state = new_state;
		switch(current_state)
		{
			case DISPLAY_MENU:
			{
				uart_string_print("============Menu==========\n");
				uart_string_print("1. Toggle Led 3\n");
				uart_string_print("2. Toggle Led 4\n");
				uart_string_print("3. Toggle Led 5\n");
				uart_string_print("4. Toggle Led 6\n");
				uart_string_print("help\n");
				uart_string_print("==========================\n");
			}
			break;
			case DISPLAY_HELP:
			{
				uart_string_print("Enter the relevant option (1/2/3/4) and press ENTER\n");

			}
			break;
			default:
			{
				uart_string_print("Incorrect option selected\n");
			}
		}
	}
}

void process_input(const led_services service)
{
	enum Leds Led_LUT[] = {
			LD3,
			LD4,
			LD5,
			LD6
	};
	for(led_services idx = SVC_LED3; idx < sizeof(Led_LUT)/sizeof(enum Leds); idx++)
	{
		if(service == Led_LUT[idx])
		{
			led_toggle(Led_LUT[service]);
			break;
		}
		else
		{
			uart_string_print("Incorrect service requested\n");
		}
	}
}

void parse_input(const queue_t * const RxQueue)
{
	char input_string[5] = {0};
	memcpy((void *)input_string, (const void *)RxQueue->storage, sizeof(input_string) - 1U);
	if(input_string[0] == '1')
	{
		process_input(SVC_LED3);
	}
	else if(input_string[0] == '2')
	{
		process_input(SVC_LED4);
	}
	else if(input_string[0] == '3')
	{
		process_input(SVC_LED5);
	}
	else if(input_string[0] == '4')
	{
		process_input(SVC_LED6);
	}
	else if(strcmp((const char *)&input_string[0], "help") == 0U)
	{

	}
}


int main(void)
{
    /* Loop forever */
	__enable_irq();
	__enable_fault_irq();
	queue_init(&TxQueue);
	queue_init(&RxQueue);
	uart_init();
	NVIC_EnableIRQ(USART2_IRQn);
	led_init();
	led_on(LD3);
	display_menu_states requested_state = DISPLAY_MENU;
	for(;;)
	{
		parse_input(&RxQueue);
		display_menu(requested_state);
		for(uint32_t idx = 0; idx < (500 * 100 * 100); idx++);
	}
}

void USART2_IRQHandler(void)
{
	if(UART_PERIPH->SR & USART_SR_RXNE)
	{
		uint8_t received = UART_PERIPH->DR;
		queue_push(&RxQueue, &received, 1);
	}
}

